service_account_email: adminwsansible@workshopansiblecoreandtower.iam.gserviceaccount.com 
credentials_file: /home/luciano/gce.json
project_id: workshopansiblecoreandtower 
chave_ssh: /home/luciano/.ssh/gce
usuario_ssh_gce: luciano
cluster_openshift: https://35.198.44.193:8443
nome_projeto_openshift: workshop-alunos
token_openshift: T7Dfu2Er-STDmQM9qqyN6eVpHJ5XvC2tCCfFbM8i7Fc
email_remetente: redhatbsb@gmail.com 
nome_workshop: workshop-ansible-bb
endereco_tower: https://35.198.12.187
url_wetty: http://wetty-single-workshop-apoio.apps.35.199.94.134.nip.io
link_form_feedback: https://goo.gl/forms/fyZAsS3Eq2H1ZQR93
