service_account_email: adminwsansible@workshopansiblecoreandtower.iam.gserviceaccount.com 
credentials_file: /home/luciano/gce.json
project_id: workshopansiblecoreandtower 
chave_ssh: /home/luciano/.ssh/gce
usuario_ssh_gce: luciano
cluster_openshift: https://35.198.30.2:8443
nome_projeto_openshift: workshop-alunos
token_openshift: SUXZzwv8tapHXYKmaisumtokensemvalidade
email_remetente: redhatbsb@gmail.com 
nome_workshop: workshop-ansible-bb
endereco_tower: https://35.198.12.187
url_wetty:  http://wetty-single-workshop-apoio.apps.35.198.30.2.nip.io

