- name: Cria instancias Gcloud Openshift para Workshop
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    machine_type_node: n1-standard-2
    zone: southamerica-east1-a
    image: centos-7
    preemptible: true
    tamanho_disco_pequeno: 40
    tamanho_disco_grande: 50
    tamanho_disco_adicional: 50
    master_private_ip: ""
    infranode_private_ip: ""
    node1_private_ip: ""

  tasks:

  - name: Carregando variaveis de config.yml
    include_vars: config.yml

  - name: "Cria Disco 1 instancia {{ user }}"
    gce_pd:
      name: "{{ user }}disk01"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Cria Instancia {{ user }}"
    gce:
        instance_names: "{{ user }}"
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: "{{ user }}disk01"
          mode: READ_WRITE
    register: gce_node


  - name: Salva dados no grupo de inventario... usuario
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_ips
    with_items: "{{ gce_node.instance_data }}"

  - name: Grava IP da instancia na variavel ip_publico
    set_fact:
      ip_publico: "{{ item.public_ip }}"
    with_items: "{{ gce_node.instance_data }}"

  - name: Espera por SSH habilitado...
    wait_for:
      delay: 1
      host: "{{ item.public_ip }}"
      port: 22
      state: started
      timeout: 30
    with_items: "{{ gce_node.instance_data }}"

  - name: "Seta variaveis para proximos passos"
    set_fact: 
      chave_ssh: "{{ chave_ssh }}"
      usuario_ssh_gce: "{{ usuario_ssh_gce }}"

  - name: Login no cluster Openshift
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc login {{ cluster_openshift }} --token={{ token_openshift }} --insecure-skip-tls-verify"

  - name: Escolhe projeto
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc project {{ nome_projeto_openshift }}"

  - name: Cria deployment Wetty aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc new-app lasher/wetty-student openshift={{ ip_publico }} --name=wetty-{{ user }} -n {{ nome_projeto_openshift }}"

  - name: Pausa gatilho DC
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc rollout pause dc wetty-{{ user }} -n {{ nome_projeto_openshift }}"

  - name: Seta limites para wetty do aluno
    shell: export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc set resources dc wetty-{{ user }} --limits=memory=50Mi -n {{ nome_projeto_openshift }}

  - name: Cria deployment Wetty aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc rollout resume dc wetty-{{ user }} -n {{ nome_projeto_openshift }}"

  - name: Cria rota para acesso ao wetty-aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc expose svc/wetty-{{ user }} -n {{ nome_projeto_openshift }}"

  - name: Obtem nome da rota wetty
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc get route wetty-{{ user }} --no-headers -n {{ nome_projeto_openshift }} | awk '{print $2}'"
    register: result_url_wetty

  - name: Cria deployment web_workshop
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc new-app LINK_FORM_FEEDBACK={{ link_form_feedback }} TOWER={{ endereco_tower }} IP_CLUSTER_OCP={{ cluster_openshift }} NOME_WORKSHOP={{ nome_workshop  }} ALUNO={{ user }} IP_INSTANCIA={{ ip_publico }} URL_WETTY=http://{{ result_url_wetty.stdout }} php~https://github.com/redhat-sa-brazil/workshop-onboarding-apps --context-dir=Workshop-PHP-Student/src  --name=web-{{ user }} "


  - name: Cria rota para acesso ao web-workshop...
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc expose svc/web-{{ user }}"

  - name: Obtem nome da rota
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc get route web-{{ user }} --no-headers -n {{ nome_projeto_openshift }} | awk '{print $2}'"
    register: result_dominio_web_workshop

  - name: Envia email com dados para acesso
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ email_remetente }}"
      password: "{{ senha_email }}"
      to: "<{{ email_aluno }}>"
      subject: "Dados para Workshop {{ nome_workshop }}"
      body: 'Seu ambiente de Workshop esta disponivel em {{ result_dominio_web_workshop.stdout }}'
    delegate_to: localhost

#- name: "Configura Hosts seguindo roles... {{ hostvars['localhost']['chave_ssh'] }} "
#  vars:
#   ansible_ssh_private_key_file: "{{ hostvars['localhost']['chave_ssh'] }}"
#  hosts: gce_instances_ips
#  become: yes
#  become_method: sudo
#  remote_user: "{{ hostvars['localhost']['usuario_ssh_gce'] }}"
#  roles:
#    - postinstall

