- name: Cria instancias Gcloud Openshift para Workshop
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    machine_type_node: n1-standard-1
    machine_type_small: g1-small
    zone: southamerica-east1-a
    region: southamerica-east1
    image: centos-7
    preemptible: false
    tamanho_disco_pequeno: 40
    tamanho_disco_grande: 50
    tamanho_disco_adicional: 50
    master_private_ip: ""
    infranode_private_ip: ""
    node1_private_ip: ""

  tasks:

  - name: Carregando variaveis de config.yml
    include_vars: config.yml

  - name: "Cria Disco 1 instancia {{ user }}"
    gce_pd:
      name: "{{ user }}disk01"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Cria Disco 1 instancia {{ user }}-server1"
    gce_pd:
      name: "{{ user }}disk02"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Cria Disco 1 instancia {{ user }}-server2"
    gce_pd:
      name: "{{ user }}disk03"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Cria ip estatico {{ user }}"
    gce_eip:
     service_account_email: "{{ service_account_email }}"
     credentials_file: "{{ credentials_file }}"
     project_id: "{{ project_id }}"
     name: "ip-{{ user }}"
     region: "{{ region }}"
     state: present


  - name: "Cria Instancia {{ user }}"
    gce:
        instance_names: "{{ user }}"
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        preemptible: "{{ preemptible }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"workshop:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKuZ7MSrvu0nYOQc+w6H1lYnfkDKctaYON5WPYdKuj8KUIaM135Aj7NK857+gvDzi8GAAjWCWx0BuHP6muuDHQD2k1oH5T5kOrXoExtIo0TXwwgeHNiuFLPRKfYL5ACWou0RMd8dvqe9g9jmc9Pu+Omzct4qG/6z/s1UX2hwzw0sGIkIUaH133IP+v9iIWiqMBZZe6GzZZOEx70uEdGumCwsVAKK18WIF1BklcrUG1wrQ69LDhuKP0zzE2mwKiDqUhaa4VLaGULP0kz/PAoZx/wrJSftKwM5oqLoV9kd/YbE01YXOYeEP4cWecBbLacWrNwrZgn6fBMpnZ6TOquMff"}'
        disks:
        - name: "{{ user }}disk01"
          mode: READ_WRITE
    register: gce_node

  - name: "Cria Instancia {{ user }}-server1"
    gce:
        instance_names: "{{ user }}-server1"
        machine_type: "{{ machine_type_small }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        external_ip: none
        preemptible: "{{ preemptible }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"workshop:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKuZ7MSrvu0nYOQc+w6H1lYnfkDKctaYON5WPYdKuj8KUIaM135Aj7NK857+gvDzi8GAAjWCWx0BuHP6muuDHQD2k1oH5T5kOrXoExtIo0TXwwgeHNiuFLPRKfYL5ACWou0RMd8dvqe9g9jmc9Pu+Omzct4qG/6z/s1UX2hwzw0sGIkIUaH133IP+v9iIWiqMBZZe6GzZZOEx70uEdGumCwsVAKK18WIF1BklcrUG1wrQ69LDhuKP0zzE2mwKiDqUhaa4VLaGULP0kz/PAoZx/wrJSftKwM5oqLoV9kd/YbE01YXOYeEP4cWecBbLacWrNwrZgn6fBMpnZ6TOquMff"}'
        disks:
        - name: "{{ user }}disk02"
          mode: READ_WRITE

  - name: "Cria Instancia {{ user }}-server2"
    gce:
        instance_names: "{{ user }}-server2"
        machine_type: "{{ machine_type_small }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        external_ip: none
        preemptible: "{{ preemptible }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"workshop:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKuZ7MSrvu0nYOQc+w6H1lYnfkDKctaYON5WPYdKuj8KUIaM135Aj7NK857+gvDzi8GAAjWCWx0BuHP6muuDHQD2k1oH5T5kOrXoExtIo0TXwwgeHNiuFLPRKfYL5ACWou0RMd8dvqe9g9jmc9Pu+Omzct4qG/6z/s1UX2hwzw0sGIkIUaH133IP+v9iIWiqMBZZe6GzZZOEx70uEdGumCwsVAKK18WIF1BklcrUG1wrQ69LDhuKP0zzE2mwKiDqUhaa4VLaGULP0kz/PAoZx/wrJSftKwM5oqLoV9kd/YbE01YXOYeEP4cWecBbLacWrNwrZgn6fBMpnZ6TOquMff"}'
        disks:
        - name: "{{ user }}disk03"
          mode: READ_WRITE

  - name: Salva dados no grupo de inventario... usuario
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_ips
    with_items: "{{ gce_node.instance_data }}"

  - name: Grava IP da instancia na variavel ip_publico
    set_fact:
      ip_publico: "{{ item.public_ip }}"
    with_items: "{{ gce_node.instance_data }}"

  - name: Espera por SSH habilitado...
    wait_for:
      delay: 1
      host: "{{ item.public_ip }}"
      port: 22
      state: started
      timeout: 30
    with_items: "{{ gce_node.instance_data }}"

  - name: Login no cluster Openshift
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc login {{ cluster_openshift }} --token={{ token_openshift }} --insecure-skip-tls-verify"

  - name: Escolhe projeto
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc project {{ nome_projeto_openshift }}"

  - name: Cria deployment Wetty aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc new-app lasher/wetty-student openshift={{ ip_publico }} --name=wetty-{{ user }} -n {{ nome_projeto_openshift }} || echo 'Ja existe'"

  - name: Pausa gatilho DC
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc rollout pause dc wetty-{{ user }} -n {{ nome_projeto_openshift }}"

  - name: Seta limites para wetty do aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc set resources dc wetty-{{ user }} --limits=memory=50Mi -n {{ nome_projeto_openshift }} || echo 'Ja existe'"

  - name: Cria deployment Wetty aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc rollout resume dc wetty-{{ user }} -n {{ nome_projeto_openshift }} || echo 'Ja existe'"

  - name: Cria rota para acesso ao wetty-aluno
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc expose svc/wetty-{{ user }} -n {{ nome_projeto_openshift }} || echo 'Ja existe'"

  - name: Obtem nome da rota wetty
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc get route wetty-{{ user }} --no-headers -n {{ nome_projeto_openshift }} | awk '{print $2}'"
    register: result_url_wetty

  - name: Cria deployment web_workshop
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc new-app LINK_FORM_FEEDBACK={{ link_form_feedback }} TOWER={{ endereco_tower }} IP_CLUSTER_OCP={{ cluster_openshift }} NOME_WORKSHOP={{ nome_workshop  }} ALUNO={{ user }} IP_INSTANCIA={{ ip_publico }} URL_WETTY=http://{{ result_url_wetty.stdout }} php~https://github.com/redhat-sa-brazil/workshop-onboarding-apps --context-dir=Workshop-PHP-Student/src --name=web-{{ user }} || echo 'Ja existe'"

  - name: Cria rota para acesso ao web-workshop...
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc expose svc/web-{{ user }} || echo 'Ja existe'"

  - name: Obtem nome da rota
    shell: "export KUBECONFIG=/tmp/kube.cfg; /usr/local/bin/oc get route web-{{ user }} --no-headers -n {{ nome_projeto_openshift }} | awk '{print $2}'"
    register: result_dominio_web_workshop

  - name: Cria usuario no tower
    tower_user:
      username: "{{ user }}"
      password: "redhat"
      email: "{{ email_aluno }}"
      first_name: "{{ user }}"
      last_name: "Workshop"
      state: present
      tower_host: "{{ endereco_tower }}"
      tower_username: "admin"
      tower_password: "redhat4ever"
      tower_verify_ssl: no
    ignore_errors: yes

#  - name: Envia email com dados para acesso
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: "{{ email_remetente }}"
#      password: "{{ senha_email }}"
#      to: "<{{ email_aluno }}>"
#      subject: "Dados para Workshop {{ nome_workshop }}"
#      body: 'Seu ambiente de Workshop esta disponivel em {{ result_dominio_web_workshop.stdout }}'
#    delegate_to: localhost

  - name:
    set_fact:
     url_estudante: "{{ result_dominio_web_workshop.stdout }}"

  - name: Gera email html do aluno
    template:
     src: /var/www/html/template_email_estudante.html
     dest: "/tmp/email_{{ user }}.html"

  - name: Envia email com dados para acesso
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ email_remetente }}"
      password: "{{ senha_email }}"
      to: "<{{ email_aluno }}>"
      subject: "Dados para Workshop {{ nome_workshop }}"
      subtype: html
      body: "{{ lookup('file', '/tmp/email_{{ user }}.html') }}"
    delegate_to: localhost

- name: "Configura Hosts seguindo roles... {{ hostvars['localhost']['chave_ssh'] }} "
  vars:
   ansible_ssh_private_key_file: "/etc/ansible/workshop-stuff/workshop_id_rsa"
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  remote_user: "workshop"
  roles:
    - postinstall-ansible

