- name:  Instalada pacotes necessários
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - docker
    - screen
    - python-rhsm-certificates
    - httpd-tools

- name: "adicionando insecure registry"
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: "^OPTIONS"
    line: "OPTIONS='--insecure-registry=172.30.0.0/16 --selinux-enabled --log-opt max-size=1M --log-opt max-file=3'"

- name: Inicia docker
  service: 
    name: docker
    state: started
    enabled: yes

- name:  Copia arquivo OC para /tmp
  copy:
    src: "{{ role_path }}/files/oc-3.9.14-linux.tar.gz"
    dest: "/tmp/oc-3.9.14-linux.tar.gz"

- name: Descompactar oc
  shell: "cd /tmp; tar -zxvf oc-3.9.14-linux.tar.gz"

- name: Copia oc para /usr/local/bin
  shell: "cp /tmp/oc /usr/local/bin"
  become: yes

- name: Clona git oc-cluster-wrapper
  shell: "mkdir /usr/local/cluster-wrapper; cd /usr/local/cluster-wrapper; git clone https://github.com/openshift-evangelists/oc-cluster-wrapper; echo 'PATH=/usr/local/cluster-wrapper/oc-cluster-wrapper:$PATH' >> $HOME/.bash_profile"
  become: yes

- name: Salva OC ClusterUP ip no profile
  shell: "echo 'export OC_CLUSTER_PUBLIC_HOSTNAME={{ inventory_hostname }}' >> $HOME/.bash_profile"
  become: yes

- name: Sobe OC ClusterUP
  shell: "export PATH=$PATH:/usr/local/bin; /usr/local/cluster-wrapper/oc-cluster-wrapper/oc-cluster up workshop --public-hostname='{{ inventory_hostname }}'"
  become: yes

#- name: Mudar senha do usuario admin
#  shell: 

#- name: Aumenta quantidade de containers do cluster
#  shell: 

- name: Login no cluster
  shell: "/usr/local/bin/oc login -u system:admin"
  become: yes

- name: Cria projeto workshop-apoio
  shell: "/usr/local/bin/oc adm new-project workshop-apoio --admin=admin"
  become: yes

- name: Da permissoes de anyuid para workshop-apoio
  shell: "/usr/local/bin/oc adm policy add-scc-to-user anyuid -z default -n workshop-apoio"
  become: yes

- name: Cria deployment Web Instructor
  shell: "/usr/local/bin/oc new-app php~https://github.com/redhat-sa-brazil/workshop-onboarding-apps --context-dir=Workshop-PHP-Instructor/src --name=web-instructor -n workshop-apoio"
  become: yes

- name: Cria rota para acesso ao web-workshop
  shell: "/usr/local/bin/oc expose svc/web-instructor -n workshop-apoio"
  become: yes

- name: Obtem nome da rota
  shell: "/usr/local/bin/oc get route web-instructor --no-headers -n workshop-apoio | awk '{print $2}'"
  become: yes
  register: result_dominio_web_workshop

- name: Criar banco de dados
  shell: "/usr/local/bin/oc new-app --template=mysql-persistent --param=MYSQL_USER=admin --param=MYSQL_DATABASE=workshop --param=MYSQL_PASSWORD=redhat@123 --param=MYSQL_ROOT_PASSWORD=redhat@123 --param=VOLUME_CAPACITY=5Gi -n workshop-apoio"
  become: yes

- name: Envia email com dados para acesso
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ username }}"
    password: "{{ pass }}"
    to: "<{{email}}>"
    subject: "Dados para Workshop Instrutor"
    body: 'O link de acesso para seu ambiente do Openshift é: https://{{ inventory_hostname }}:8443<br>Seu ambiente de Workshop esta disponivel em {{ result_dominio_web_workshop.stdout }}'
  delegate_to: localhost
  become: yes


