- name: Fix Metrics
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: OpenShift Login
      shell: oc login -u system:admin --insecure-skip-tls-verify
    - name: Get Metrics Error Pod
      shell: oc get pods -n openshift-infra | grep Error | head -n1 | cut -d' ' -f1
      register: metrics_pod
      until: metrics_pod.stdout != ""
      retries: 20
      delay: 30
    - name: Fix Metrics Deployment
      shell: >
        oc debug "{{ metrics_pod.stdout }}" -n openshift-infra -- /usr/bin/bash -c "sed -i 's/- include: validate_hostnames.yml/#- include: validate_hostnames.yml/' /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/std_include.yml &&  ansible-playbook -i /tmp/inventory playbooks/byo/openshift-cluster/openshift-metrics.yml"
