- name:  Cria usuario ansible-core
  user:
    name: workshop
    comment: "Usuario Workshop"
    uid: 2222

# contribuicao de Jose Ricardo
- name: Cria diretorio ansible-core
  file:
    path: /workshop/templates
    state: directory
    owner: ansible-core
    recurse: yes

- name: "Copiando chaves de ssh privada"
  copy:
   src: "{{ role_path }}/files/id_rsa"
   dest: /workshop/chave
   owner: workshop
   mode: 0600

- name: "Copiando arquivo de repositorio"
  copy:
   src: "{{ role_path }}/files/redhat.repo"
   dest: /workshop/redhat.repo

- name: "Copiando arquivo de fix para repo"
  copy:
   src: "{{ role_path }}/files/fix_repo_local.yml"
   dest: /workshop/fix_repo_local.yml

- name: "Copiando arquivo httpd.conf para repo"
  copy:
   src: "{{ role_path }}/files/httpd.conf.j2"
   dest: /workshop/templates/httpd.conf.j2
