- name: Ensure user luciano is present
  win_user:
    name: luciano
    password: redhat@123
    state: present
    groups:
      - Users

- name: ensure IIS and ASP.NET are installed
  win_feature:
    name: AS-Web-Support

- name: ensure application dir exists
  win_file:
    path: c:\inetpub\foo
    state: directory

- name: ensure default.aspx is present
  win_copy:
    src: "{{ role_path }}/files/default.aspx"
    dest: c:\inetpub\foo\default.aspx

- name: ensure that the foo web application exists
  win_iis_webapplication:
    name: foo
    physical_path: c:\inetpub\foo
    site: Default Web Site

#- name: ensure that application responds properly
#  uri:
#    url: "http://{{ public_ip }}/foo"
#    return_content: yes
#  register: uri_out
#  delegate_to: localhost
#  until: uri_out.content | search("Hello from")
#  retries: 3

- debug:
    msg: "web application is available at http://{{ public_ip }}/foo"

